// Seccion DOM: container
var body = document.getElementById('body');
var container = document.createElement('div');
container.classList.add('container');
body.appendChild(container);
var h1 = document.createElement('h1');
var h1Text = document.createTextNode('Generador de contraseñas');
h1.appendChild(h1Text);
container.appendChild(h1);
// Sección DOM: mostrar contraseña
var divShow = document.createElement('div');
divShow.classList.add('div-show');
container.appendChild(divShow);
var divPassword = document.createElement('div');
var divCopy = document.createElement('div');
var divRefresh = document.createElement('div');
divShow.appendChild(divPassword);
divShow.appendChild(divCopy);
divShow.appendChild(divRefresh);
divPassword.classList.add('password-section');
var textInit = document.createTextNode('e4¡qQ<>98hGFFTh');
divPassword.appendChild(textInit);
var iconCopy = document.createElement('img');
iconCopy.setAttribute('src', './assets/copy.png');
iconCopy.setAttribute('alt', 'copy icon');
divCopy.classList.add('icons');
var iconRefresh = document.createElement('img');
iconRefresh.setAttribute('src', './assets/refresh.png');
iconRefresh.setAttribute('alt', 'refresh icon');
divRefresh.classList.add('icons');
divCopy.appendChild(iconCopy);
divRefresh.appendChild(iconRefresh);
// Sección DOM: configurar contraseña
var divConfig = document.createElement('div');
divConfig.classList.add('div-config');
container.appendChild(divConfig);
var h4 = document.createElement('h6');
var h4Text = document.createTextNode("Personalice su contraseña");
h4.classList.add('text-personalize');
h4.appendChild(h4Text);
divConfig.appendChild(h4);
var divSpecificConfig = document.createElement('div');
var divLength = document.createElement('div');
var divRules = document.createElement('div');
var divCaracter = document.createElement('div');
divLength.classList.add('select-config');
divRules.classList.add('select-config');
divCaracter.classList.add('select-config');
divConfig.appendChild(divSpecificConfig);
divSpecificConfig.classList.add('specific-config');
divSpecificConfig.appendChild(divLength);
divSpecificConfig.appendChild(divRules);
divSpecificConfig.appendChild(divCaracter);
var h6Length = document.createElement('h6');
var h6LengthText = document.createTextNode("Longitud");
var h6Rules = document.createElement('h6');
var h6RulesText = document.createTextNode("Reglas");
var h6Caracter = document.createElement('h6');
var h6CaracterText = document.createTextNode("Caracteres");
divLength.appendChild(h6Length);
h6Length.appendChild(h6LengthText);
divRules.appendChild(h6Rules);
h6Rules.appendChild(h6RulesText);
divCaracter.appendChild(h6Caracter);
h6Caracter.appendChild(h6CaracterText);
var form = document.createElement('form');
//Longitud de contraseña
var selectLength12 = document.createElement('div');
var selectLength9 = document.createElement('div');
var selectLength6 = document.createElement('div');
var labelTwelveCaracter = document.createElement('label');
labelTwelveCaracter.setAttribute("for", "checkTwelve");
labelTwelveCaracter.textContent = "12 caracteres";
var twelveCaracter = document.createElement('input');
twelveCaracter.setAttribute("type", "radio");
twelveCaracter.setAttribute("id", "checkTwelve");
var labelNineCaracter = document.createElement('label');
labelNineCaracter.setAttribute("for", "checkNine");
labelNineCaracter.textContent = "9 caracteres";
var nineCaracter = document.createElement('input');
nineCaracter.setAttribute("type", "radio");
nineCaracter.setAttribute("id", "checkNine");
var labelSixCaracter = document.createElement('label');
labelSixCaracter.setAttribute("for", "checkSix");
labelSixCaracter.textContent = "6 caracteres";
var sixCaracter = document.createElement('input');
sixCaracter.setAttribute("type", "radio");
sixCaracter.setAttribute("id", "checkSix");
form.appendChild(selectLength12);
form.appendChild(selectLength9);
form.appendChild(selectLength6);
divLength.appendChild(form);
selectLength12.appendChild(twelveCaracter);
selectLength12.appendChild(labelTwelveCaracter);
selectLength9.appendChild(nineCaracter);
selectLength9.appendChild(labelNineCaracter);
selectLength6.appendChild(sixCaracter);
selectLength6.appendChild(labelSixCaracter);
